packages:
  - name: rva-queer-soccer-bot
    functions:
      - name: rva-queer-soccer-bot
        binary: false
        runtime: python:default
        web: false
        triggers:
          - name: rva-queer-soccer-bot
            sourceType: scheduler
            sourceDetails:
              cron: "0 11 * * 0,3"
        environment:
          TOKEN: "${TOKEN}"
